# Generated by Django 4.0.4 on 2022-05-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digest',
            name='digest_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='digest_text',
            field=models.TextField(),
        ),
    ]
