# Generated by Django 4.0.4 on 2022-05-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApplication', '0002_alter_digest_digest_text_alter_review_digest_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='digest_text',
            new_name='review_text',
        ),
        migrations.RemoveField(
            model_name='review',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
